// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFgoWYZKj-iX7TrMXdzT3A5zkOYRBBDB4',
    appId: '1:84064595774:android:446b8a074e9d97cec7066f',
    messagingSenderId: '84064595774',
    projectId: 'talentia-cbdf6',
    storageBucket: 'talentia-cbdf6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVxPhLLBeviQo39ioq24S5AwxqWun6mgM',
    appId: '1:84064595774:ios:93f21a11be37f940c7066f',
    messagingSenderId: '84064595774',
    projectId: 'talentia-cbdf6',
    storageBucket: 'talentia-cbdf6.firebasestorage.app',
    androidClientId: '84064595774-lneq4tfn60se1g5v18m4q9a65ftkkmhs.apps.googleusercontent.com',
    iosClientId: '84064595774-uueekog4k2l06hr1s33gjiseec0oat3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.talentia',
  );
}
